# -*- coding: utf-8 -*-
from . import gms_camiones
from . import gms_propiedades
from . import gms_rutas
from . import gms_viajes
from . import product_template
from . import res_partner
from . import gms
from . import gms_gastoViaje
from . import gms_agenda
from . import gms_disponibilidad
from . import gms_disponibilidad_2
from . import gms_historial
from . import gms_stock_picking
from . import gms_sale_order
from . import purchase_order
from . import gms_medidas_propiedad
from . import gms_propiedades_lineas
from . import gms_tolva
from . import gms_ajustes
from . import res_config_settings
from . import gms_modelo_asistente
from . import gms_balanza
from . import account_move
